# Generated by Django 2.2.5 on 2019-09-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PracticeDrills',
            new_name='PracticeDrill',
        ),
    ]
