service: schedule-generator

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  apiName: PracticePalSimpleProxy
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/practice_drill
        - arn:aws:dynamodb:us-east-1:*:table/practice_drill/index/skill_level-index
        - arn:aws:s3:::practice-pal/*
  versionFunctions: false

package:
  include:
    - lambda_functions/**
  exclude:
    - .idea/**
    - .gitignore
    - LICENSE
    - README.md
    - node_modules/**
    - venv/**

functions:
  practiceDrillGet:
    handler: lambda_functions.practice_drill.get
    environment:
      TABLE_NAME: practice_drill
    events:
      - http: GET practice-drill
  updatePracticeDrillDynamo:
    handler: lambda_functions.update_practice_drill_dynamo.lambda_handler
    environment:
      TABLE_NAME: practice_drill


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
